listenAddress: :8080
serialPort: /dev/ttyUSB0

ldapEnabled: false
ldapHosts: [ "server1:3269", "server2:3269" ]
ldapBaseDn: "dc=company,dc=example,dc=org"
ldapUserSearchFilter: "(&(sAMAccountType=805306368)(sAMAccountName=%s)(|((memberof:1.2.840.113556.1.4.1941:=CN=admins,dc=company,dc=example,dc=org)(uid=serviceaccount)))"
ldapBindDn: readonlyuser
ldapBindPassword: base64-encoded-password

authTokenSiningKey: base64-encoded-string
initialAdminPassword: base64-encoded-string